parameters:
  fl_facebook_pages.facebook_client_config:
    app_id: '%fl_facebook_pages.app_id%'
    app_secret: '%fl_facebook_pages.app_secret%'
    default_graph_version: 'v3.1'
    enable_beta_mode: false
    persistent_data_handler: ~
    pseudo_random_string_generator: ~
    url_detection_handler: ~

services:
  fl_facebook_pages.facebook_client:
    class: Facebook\Facebook
    arguments: ['%fl_facebook_pages.facebook_client_config%']

  fl_facebook_pages.facebook.page_manager_client:
    class: FL\FacebookPagesBundle\Services\Facebook\PageManagerClient
    arguments:
      - '%fl_facebook_pages.app_id%'
      - '%fl_facebook_pages.page_manager_class%'
      - '%fl_facebook_pages.page_class%'
      - '%fl_facebook_pages.page_review_class%'
      - '@fl_facebook_pages.facebook_client'
