fl_facebook_pages_routes:
  resource: "@FLFacebookPagesBundle/Resources/config/routing/action/authorization.yml"
  resource: "@FLFacebookPagesBundle/Resources/config/routing/action/webhook/rating.yml"
