imports:
    - { resource: 'services/action/authorization.yml' }
    - { resource: 'services/action/webhook/rating.yml' }
    - { resource: 'services/facebook/v2-8/clients.yml' }
    - { resource: 'services/guzzle/guzzle.yml' }
