imports:
    - { resource: 'services/action/auth.yml' }
    - { resource: 'services/action/webhook.yml' }
    - { resource: 'services/facebook/clients.yml' }
    - { resource: 'services/guzzle/guzzle.yml' }
    - { resource: 'services/storage/doctrine.yml' }
