services:
  fl_facebook_pages.facebook.v2_8.page_manager_client:
    class: FL\FacebookPagesBundle\Services\Facebook\V2_8\PageManagerClient
    arguments:
      - "%fl_facebook_pages.app_id%"
      - "%fl_facebook_pages.app_secret%"
      - "%fl_facebook_pages.page_manager_class%"
      - "%fl_facebook_pages.page_class%"
      - "%fl_facebook_pages.page_review_class%"
      - "@fl_facebook_pages.guzzle.client"
