services:
  fl_facebook_pages.storage.doctrine.page_manager_storage:
    class: FL\FacebookPagesBundle\Storage\DoctrineORM\PageManagerStorage
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%fl_facebook_pages.page_manager_class%"
    lazy: true

  fl_facebook_pages.storage.doctrine.page_storage:
    class: FL\FacebookPagesBundle\Storage\DoctrineORM\PageStorage
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%fl_facebook_pages.page_class%"
    lazy: true

  fl_facebook_pages.storage.doctrine.page_review_storage:
    class: FL\FacebookPagesBundle\Storage\DoctrineORM\PageReviewStorage
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%fl_facebook_pages.page_review_class%"
    lazy: true
