services:
  'FL\FacebookPagesBundle\Action\AuthorizeFacebook':
    class: FL\FacebookPagesBundle\Action\AuthorizeFacebook
    arguments:
      - "@fl_facebook_pages.facebook.v2_8.user_client"
      - "%fl_facebook_pages.callback_url%"

  'FL\FacebookPagesBundle\Action\SaveAuthorization':
    class: FL\FacebookPagesBundle\Action\SaveAuthorization
    arguments:
      - "@fl_facebook_pages.facebook.v2_8.user_client"
      - "@?fl_facebook_pages.facebook_user_storage"
      - "@?fl_facebook_pages.page_storage"
      - "%fl_facebook_pages.redirect_url_after_authorization%"
      - "%fl_facebook_pages.only_these_page_ids%"
